# Generated by Django 6.0.3 on 2026-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSnapshot',
        ),
    ]
