# Generated by Django 6.0.3 on 2026-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='event',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceCode',
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
