# Generated by Django 6.0.3 on 2026-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobmatch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobmatch',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobmatch',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobOpportunity',
        ),
        migrations.DeleteModel(
            name='JobMatch',
        ),
    ]
