# Generated by Django 6.0.3 on 2026-03-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('community', 'Community'), ('social', 'Social'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('leadership', 'Leadership'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='upcoming', max_length=20)),
                ('emoji', models.CharField(default='📅', max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(default=50)),
                ('roles_available', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date'],
            },
        ),
    ]
