# Generated by Django 6.0.3 on 2026-05-25 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
        ('points', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='reason',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('event_attendance', 'Event Attendance'), ('volunteer_checkin', 'Volunteer Check-in'), ('event_share', 'Event Share'), ('task_completed', 'Task Completed'), ('cv_uploaded', 'CV Uploaded'), ('referral', 'Referral'), ('bonus', 'Bonus'), ('deduction', 'Deduction')], max_length=30),
        ),
        migrations.CreateModel(
            name='EventShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded', models.BooleanField(default=False)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='events.event')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_shares',
                'unique_together': {('event', 'shared_by')},
            },
        ),
    ]
