# Generated by Django 6.0.3 on 2026-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
