# Generated by Django 6.0.3 on 2026-03-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('support', 'General Support'), ('partnership', 'Partnership Proposal'), ('event', 'Event Suggestion'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contact_forms',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
