# Generated by Django 6.0.3 on 2026-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='announcement',
            table=None,
        ),
    ]
